
REDIS_HOST="127.0.0.1"
REDIS_PORT = 6379
REDIS_DB = 4
REDIS_USERNAME = ''
REDIS_PASSWORD = ''
REDIS_URL = f'redis://{REDIS_USERNAME}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'
POSTGRES_HOST = '127.0.0.1'
POSTGRES_PORT = 5432
POSTGRES_DB = 'dev'
POSTGRES_USERNAME = 'postgres'
POSTGRES_PASSWORD = '123456'